#!/bin/bash
# usage -
# convertdoc {fromfile} {tofile}

if [ $# != 2 ]
then
  echo "Try this"
  echo "$0 README.md README.pdf"
else
  docker run --rm -v /var/lib/docker/vsonlinemount/workspace/ECM3440-docker:/data jpbernius/pandoc -o $2 $1
fi
